Repository CSwala/awesome-computer-science, pull requests merged in 2021-04, with the labels that each got.

#202 Add openshift
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#204 Add Ionic
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#205 Add Solidity
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#195 Fix #61: Add cryengine to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#209 Game maker Added
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#214 Fix #20: Add Perl
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#216 Fix #60 : Add Buildbox
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#218 Fix #210 Added CSS
  Dictionary.json
  README.md
Labels: Level2, gssoc21

#224 Fix #217 : Added Next.js
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#231 Add Zig
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#236 #235 Remove bug
  Dictionary.json
Labels: Level0, gssoc21

#225 Fix #220 Added .NET
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#233 Fix #232 Added Apache Tomcat
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#245 fix dictionary.json
  Dictionary.json
Labels: Level0, gssoc21

#246 FIX #234 : ADD PURESCRIPT
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#253 Fix #157: Add Machine Learning
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#256 Fix #254: Added checklist in PULL_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Level0, gssoc21

#257 Fix #227: Add React Native
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#258 Add Reason
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#263 Fix#226 : Add TypeScript
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#265 Fix #18: Added MATLAB
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#267 Vanilla Javascript.Fixes #264
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#269 Add Nim
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#272 Fix #270: Add Apex
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#261 Fix #260: Changes in Dictionary.json
  Dictionary.json
Labels: Level1, gssoc21

#284 Fix #283 : Add Unix
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#286 Added OCaml
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#292 Added Erlang
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#291 Fix #290 : Add Pascal
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#289 Fix #4: Add Flutter resources
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#288 Added MERN Stack
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#295 Fix #228: Add MySQL
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#296 Fix #239: Added Artificial intelligence
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#300 Added Elm
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#336 Fix #305 [Added resources for GCP]
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#350 Fixes #335 :Readme updated
  README.md
Labels: Level0, gssoc21

#334 Fix Issue #333 Added Jekyll
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#357 Fix #303 [Added resources for DevOps]
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#375 Fix #324: Add Tailwind CSS
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#374 Fixes #337:Added RoR
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#389 Fixes #339: Yii Framework
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#397 Fix #356: Added pygame
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#413 Fix #314: Add Xamarin
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#402 Fix #379 : Add NetworkX
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#440 Fix #237 Added Linux
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#436 Qlik Sense Added
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#435 Fix #341 :Add Adobe Illustartor
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#433 Fix #362:Added Zend Framework
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#432 Added Xcode
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#428 Added JSX
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#427 Fix #378 Added Computer Networks
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#441 Fix #434 :Added Play Framework
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#443 Fix issue #353
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#452 Fix #411: Added resources for Octave
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#449 Fix issue #369 Add Deep Learning
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#454 Fix #273 Added Data Mining
  Dictionary.json
  README.md
Labels: Level1, gssoc21
