Repository CSwala/awesome-computer-science, pull requests merged in 2021-03, with the labels that each got.

#107 Fix #86: Add Puppet to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#110 Fix #85: Added ansible to the database: Correction
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#112 Fix 85: Added blender to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#115 fix-pandas
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#116 Fix #43: Added postgresql to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#119 Fix #82: Added DirectX to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#122 Fix #14: Add swift to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#125 Fix #10: Add nodejs to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#127 Fix #6 : Added Django
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#130 fix-numpy
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#129 Fix #90 & Fix #87 : Add Jira and Vagrant to the Database
  Dictionary.json
  README.md
Labels: Level3, enhancement, gssoc21

#134 Fix #55: Add unity to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#133 Fix #132 and #83 : Added WebGL and Alphabetically Sorted ReadMe
  Dictionary.json
  README.md
Labels: Level3, gssoc21

#139 Fix #33: Add keras to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#142 Fix #35: Add pytorch to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#168 Fix #152: Added Heroku
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#185 Fix #155: Add kibana to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#187 Fix #147: Add elasticsearch to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#188 Fix #151: Add hbase to the database
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#191 Add iOS
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#194 Add TeamCity
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#193 Elixir Added
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#197 Add Apache Spark
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#198 Fix #23: Added Rust
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#200 add godot
  Dictionary.json
  README.md
Labels: Level1, gssoc21
