Repository CSwala/awesome-computer-science, pull requests merged in 2021-05, with the labels that each got.

#467 Fix 405: Added ASP
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#470 Fix #317: Added HTTP
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#471 Fix issue #400 Add Beautiful Soup Library
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#472 Fix issue #446 Add SciLab
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#490 Fix #484 : Added Cryptography
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#501 Fix issue #453 Add Cyber Security
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#499 Fix issue #450 Adding TinkerCAD
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#508 Fix issue #458 Add Ethical Hacking
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#531 Fix #342:Requests Added
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#549 Fixed Bug #548 : Vulkan Logo is Unavailable
  Dictionary.json
  README.md
Labels: Level0, gssoc21

#607 Fix #536: Turbogears added
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#609 Fix #573: Added backbone.js
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#610 Fix #575: Added Aurelia
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#611 Fixes #465: Add WebRTC
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#612 Fix #571: Cloudforms added
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#618 Added Neo4j
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#616 Add Semi-Supervised-Learning
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#624 Added Backend development
  Dictionary.json
  README.md
Labels: Level2, gssoc21

#629 Fixes #529: Added AnimeJS
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#630 Fixes #526: Add Material UI
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#631 Fixes #528: Add PassportJS
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#632 Added JSP(Jakarta Server Pages)
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#635 Added JSON
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#638 Fix #543 : Added JWT
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#637 Added Netwide Assembler
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#639 Added Consul
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#648 Added OpenStack
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#650 Added J(Programming language)
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#649 Added Spinnaker
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#524 Fix #343 : Sql Added
  Dictionary.json
  README.md
Labels: Level1, gssoc21

#653 Fix #479: Add Objective C
  Dictionary.json
  README.md
Labels: Level1, gssoc21
